[media-source]
exten => 6000,1,Answer()
 same => n,Echo()
 same => n,Hangup()

[from-twilio]
exten => _X.,1,Set(__AIAVATAR_SESSION_ID=${UNIQUEID})
 same => n,Set(__AIAVATAR_CALLED_NUMBER=${EXTEN})
 same => n,Stasis(aiavatar,inbound)
 same => n,Hangup()

