from .base import (
    QuickResponder,
    DEFAULT_QUICK_RESPONSE_PROMPT_PREFIX,
    DEFAULT_QUICK_RESPONSE_PROMPT_PREFIX_JA,
    DEFAULT_REQUEST_PREFIX,
    DEFAULT_REQUEST_PREFIX_JA,
    DEFAULT_FALLBACK_PHRASES,
    DEFAULT_FALLBACK_PHRASES_JA
)
from .pro import (
    QuickResponderPro,
    DEFAULT_QRP_SYSTEM_PROMPT,
    DEFAULT_QRP_SYSTEM_PROMPT_JA,
    DEFAULT_QRP_PROMPT_PREFIX,
    DEFAULT_QRP_PROMPT_PREFIX_JA,
    DEFAULT_QRP_THINK_TAG_CONTENT,
    DEFAULT_QRP_THINK_TAG_CONTENT_JA,
    DEFAULT_QRP_REQUEST_PREFIX,
    DEFAULT_QRP_REQUEST_PREFIX_JA,
    DEFAULT_QRP_CONTINUATION_MESSAGE,
    DEFAULT_QRP_CONTINUATION_MESSAGE_JA,
    DEFAULT_QRP_FALLBACK_PHRASES,
    DEFAULT_QRP_FALLBACK_PHRASES_JA
)
